spring.application.name=assistant
#
#export SPRING_AI_OPENAI_API_KEY=...
#
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
#
spring.ai.mcp.client.streamable-http.connections.scheduler.url=http://localhost:8081
spring.ai.mcp.client.initialized=false
spring.ai.vectorstore.pgvector.dimensions=1024
#
logging.level.org.springframework.ai=DEBUG
logging.level.org.springaicommunity=DEBUG
#
spring.ai.bedrock.converse.chat.options.model=amazon.nova-pro-v1:0
spring.ai.model.embedding=bedrock-cohere
#
spring.ai.vectorstore.pgvector.initialize-schema=true
#
#  NEW in 0.1.5
spring.ai.mcp.client.authorization.dynamic-client-registration.enabled=true
#
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always