spring.application.name=assistant
#
#export SPRING_AI_OPENAI_API_KEY=...
#
spring.datasource.password=secret
spring.datasource.username=myuser
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
#
spring.ai.mcp.client.streamable-http.connections.scheduler.url=http://localhost:8081
spring.ai.mcp.client.initialized=false
#
spring.ai.vectorstore.pgvector.initialize-schema=true
#
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always